server {
    listen 80;
    server_name skpi.dwijacode.my.id;

    # Sesuai dengan working_dir di docker-compose skpi_php
    root /var/www/html/public; 
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass skpi:9000;
        fastcgi_index index.php;
        # Pastikan baris ini menggunakan $document_root
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}