server {
    listen 80;
    server_name skpi.dwijacode.my.id;

    # Root ke public directory Laravel
    root /var/www/html/skpi/public;
    index index.php index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass skpi:9000;  # Nama service PHP
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        include fastcgi_params;
        fastcgi_index index.php;
    }

    location ~ /\.(ht|git|env) {
        deny all;
    }
}
